# Copied from https://github.com/stefanbuck/instantiated-templatelate

name: Setup repository
on:
  workflow_call:
    inputs:
      branch_name:
        type: string
        description: The branch to push to after instantiating the template.
        required: true

    secrets:
      token:
        description: >-
          The token to use for committing to the repo. It requires `workflow`
          scope in order to commit changes to the .github/ workflow files.
        required: true

jobs:
  setup:
    name: Reinitialize repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.token }}

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install cruft

      - name: Scaffolding repository
        run: cruft create . --no-input --output-dir ./instantiated-template

      - name: Prepare root directory
        shell: bash
        # Remove all files and folder except .git/ and instantiated-template/
        run: |
          find ./ -maxdepth 1 \
          ! -name '.git' \
          ! -name 'instantiated-template' \
          ! -name '.' \
          ! -exec rm -rf {} +

      - name: Move files to root
        shell: bash
        # The instantiated-template/ folder contains a single folder which is the
        # generated project by cookiecutter. We want to move all the project
        # files into the root directory so we can reinitialize git in the next step
        run: |
          rsync -r ./instantiated-template/*/ . && \
          rm -rf ./instantiated-template/

      - name: Reinitialize git repository
        shell: bash
        # Reinitialize git after scaffolding this repository.
        # We use `git checkout --orphan` to create a branch in a git init-like state.
        # By force pushing this as the new branch we end up with a new clean git history.
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com" && \
          git config --global user.name "github-actions[bot]" && \
          git checkout --orphan temp-branch && \
          git add . && \
          git commit -m 'Initial commit' && \
          git push origin temp-branch:${{ inputs.branch_name }} -f
