name: Setup repository
on:
  push:
    paths:
      - cookiecutter.json

jobs:
  require-non-template:
    name: Check that the current repo is not the original template repo
    runs-on: ubuntu-latest
    env:
      REPO_SETUP_TOKEN: ${{ secrets.REPO_SETUP_TOKEN }}
    steps:
      - name: Do not run scaffolding on template repository
        shell: bash
        # This workflow runs when the `cookiecutter.json` file is modified.
        # This is the trick to re-init a repository, but we don't want to
        # run this action if this file is modified in the origin template repository.
        #
        # Using the GitHub rest API allows us to identify if the current repository
        # is a template repository or not.
        run: |
          curl --silent -X GET \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.baptiste-preview+json" \
            https://api.github.com/repos/$GITHUB_REPOSITORY \
            | jq --exit-status '.is_template == false';

  setup-repository:
    name: Instantiate repo template
    uses: ./.github/workflows/cookiecutter.yml
    with:
      # Commit directly to the main branch, erasing the history of the template
      branch_name: main
      token: ${{ secrets.REPO_SETUP_TOKEN }}
