name: Setup repository
on:
  workflow_dispatch:
  push:
    branches:
      # Technically this might not work if someone used a different default branch,
      # but let's assume that it will always be called "main"
      - main
    paths:
      - cookiecutter.json

jobs:
  require-non-template:
    name: Check that the current repo is not the original template repo
    runs-on: ubuntu-latest
    steps:
      - name: Do not run scaffolding on template repository
        shell: bash
        # This workflow runs when the `cookiecutter.json` file is modified.
        # This is the trick to re-init a repository, but we don't want to
        # run this action if this file is modified in the origin template repository.
        #
        # Using the GitHub rest API allows us to identify if the current repository
        # is a template repository or not.
        env:
          REPO_SETUP_TOKEN: ${{ secrets.REPO_SETUP_TOKEN }}
        run: |
          echo "https://api.github.com/repos/${GITHUB_REPOSITORY}" && \
          curl --fail -X GET \
            -H "Accept: application/vnd.github.baptiste-preview+json" \
            -H "Authorization: token ${REPO_SETUP_TOKEN}" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}" \
            | jq --exit-status '.is_template | not'

  setup-repository:
    name: Instantiate repo template
    needs: require-non-template
    uses: ./.github/workflows/cookiecutter.yml
    with:
      # Commit directly to the main branch, erasing the history of the template
      branch_name: main
    secrets:
      token: ${{ secrets.REPO_SETUP_TOKEN }}

  cleanup:
    name: Cleanup remaining secret
    needs: setup-repository
    runs-on: ubuntu-latest
    steps:
      - name: Remove secret REPO_SETUP_TOKEN
        # After re-initializing the repository, we can remove the `REPO_SETUP_TOKEN` secret.
        shell: bash
        env:
          REPO_SETUP_TOKEN: ${{ secrets.REPO_SETUP_TOKEN }}
        if: ${{ env.REPO_SETUP_TOKEN != '' }}
        run: |
          curl \
            -X DELETE --fail \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${REPO_SETUP_TOKEN}" \
            https://api.github.com/repos/$GITHUB_REPOSITORY/actions/secrets/REPO_SETUP_TOKEN

