name: Template CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  initialize:
    name: Instantiate repo template
    uses: ./.github/workflows/cookiecutter.yml
    with:
      branch_name: ci/${{ github.ref_name }}
    secrets:
      token: ${{ secrets.REPO_SETUP_TOKEN }}

  template-ci:
    name: Run CI on the instantiated template
    runs-on: ubuntu-latest
    needs:
      - initialize
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SETUP_TOKEN }}

      - name: Trigger CI against template branch
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: ci.yml
          token: ${{ secrets.REPO_SETUP_TOKEN }}
          ref: ci/${{ github.ref_name }}

      - name: Clean up test branch
        shell: bash
        run: git push origin --delete ci/${{ github.ref_name }}
